POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Hodor",
  "email": "hodor@weHoldDoors.com",
  "address": "Casterly Rock, Westerlands",
  "dateOfBirth": "1995-01-01",
  "registeredDate": "2024-01-01"
}